/**
 * Build the maneuver library, once, and write it into the demo as data.
 *
 * This is the whole architecture in one script. Everything expensive —
 * instantiating each template for each sofa, validating every placement and
 * every edge against the collider, measuring what each motion demands of a
 * doorway — happens here, at build time, and what ships to a browser is a table
 * of numbers and a few paths to animate.
 *
 * The hero's planner figures are here for the same reason and a stronger one:
 * a 90 cm doorway takes the general planner about ten seconds to fail to
 * answer, and nobody is going to sit through that on a product page. The point
 * of showing it is that it happened, not that it happens now.
 *
 * Run by `npm run precompute`, which `npm run build` runs first. The output is
 * committed so that `npm run dev` works without it.
 */
import { writeFileSync, mkdirSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';
import {
  MODULES,
  SOFAS,
  buildEnvironment,
  buildLibrary,
  plan,
  provableNoFit,
  reportOn,
} from '../../../packages/engine/src/index.ts';
import { prepareItem } from '../../../packages/engine/src/geometry/collide.ts';
import type { EnvironmentParams } from '../../../packages/engine/src/index.ts';

const WALL = 15;
const HERO_WIDTH = 90;
const HERO_BUDGET = 1_200_000;

/** Round every number in the payload, so the shipped file is not full of noise. */
function tidy<T>(value: T): T {
  return JSON.parse(
    JSON.stringify(value, (_key, v: unknown) =>
      typeof v === 'number' && Number.isFinite(v) ? Number(v.toFixed(4)) : v,
    ),
  ) as T;
}

const hero: EnvironmentParams = {
  openingWidth: HERO_WIDTH,
  openingHeight: 210,
  wallThickness: WALL,
  hallwayWidth: 300,
  hallwayDepth: 320,
  roomDepth: 400,
  roomWidth: 400,
  ceilingHeight: 250,
};

console.log('building the library…');
const catalogue = SOFAS.map((item) => {
  const started = performance.now();
  const report = reportOn(item, WALL);
  const { maneuvers } = buildLibrary(prepareItem(item), WALL);
  const modules = (MODULES[item.id] ?? []).map((piece) => ({
    id: piece.id,
    report: reportOn(piece, WALL),
  }));
  console.log(
    `  ${item.name.padEnd(28)} ${(report.narrowest ?? NaN).toFixed(2)} cm  ` +
      `(${(performance.now() - started).toFixed(0)}ms)`,
  );
  return { id: item.id, report, maneuvers, modules };
});

// The hero, both engines, on the same question.
const heroItem = SOFAS[0]!;
const heroEnvironment = buildEnvironment(hero);
const heroEntry = catalogue.find((entry) => entry.id === heroItem.id)!;

const selectionStarted = performance.now();
const heroFits = heroEntry.maneuvers
  .filter(
    (m) =>
      m.requirement.doorWidth <= hero.openingWidth &&
      m.requirement.doorHeight <= hero.openingHeight &&
      m.requirement.hallwayClearance <= hero.hallwayWidth &&
      m.requirement.roomDepth <= hero.roomDepth,
  )
  .sort((a, b) => a.stages.length - b.stages.length)[0];
const selectionMicros = (performance.now() - selectionStarted) * 1000;
if (heroFits === undefined) throw new Error('the hero doorway has no maneuver, which defeats the point');

console.log(`planning the hero the hard way (up to ${HERO_BUDGET.toLocaleString('en-US')} nodes)…`);
const plannerStarted = performance.now();
const planned = plan(heroItem, heroEnvironment, { diagnostics: false, maxNodes: HERO_BUDGET });
const plannerMs = performance.now() - plannerStarted;
console.log(
  `  planner: ${planned.feasible ? 'feasible' : planned.reason} in ${plannerMs.toFixed(0)}ms, ` +
    `${planned.stats.nodesGenerated.toLocaleString('en-US')} nodes`,
);

const payload = tidy({
  wallThickness: WALL,
  catalogue,
  hero: {
    params: hero,
    itemId: heroItem.id,
    library: {
      templateId: heroFits.templateId,
      name: heroFits.name,
      nameHe: heroFits.nameHe,
      requirement: heroFits.requirement,
      stages: heroFits.stages,
      path: heroFits.path,
      micros: Math.max(1, Math.round(selectionMicros)),
    },
    planner: {
      feasible: planned.feasible,
      reason: planned.feasible ? 'feasible' : planned.reason,
      nodes: planned.stats.nodesGenerated,
      ms: Math.round(plannerMs),
      budget: HERO_BUDGET,
    },
    // The closed-form proof, asked the same question, so the page can show all
    // three answers side by side and label which one spoke.
    proof: provableNoFit(heroItem.boxes, hero.openingWidth, hero.openingHeight),
  },
});

const here = dirname(fileURLToPath(import.meta.url));
const out = resolve(here, '../src/precomputed.ts');
mkdirSync(dirname(out), { recursive: true });

const banner = `/**
 * GENERATED by scripts/precompute.ts. Do not edit by hand.
 *
 * The maneuver library for every sofa in the catalogue, built and validated
 * offline, plus the hero's two answers to the same question. Regenerated by
 * \`npm run precompute\`, which the build runs first.
 */
import type { ItemReport, Maneuver, ManeuverRequirement, ManeuverStage } from '@fitpath/engine';
import type { EnvironmentParams, NoFitProof, Placement } from '@fitpath/engine';

export interface CatalogueModule {
  id: string;
  report: ItemReport;
}

export interface CatalogueEntry {
  id: string;
  report: ItemReport;
  maneuvers: Maneuver[];
  modules: CatalogueModule[];
}

export interface HeroLibraryAnswer {
  templateId: string;
  name: string;
  nameHe: string;
  requirement: ManeuverRequirement;
  stages: ManeuverStage[];
  path: Placement[];
  /** How long the runtime selection took, in microseconds. */
  micros: number;
}

export interface HeroPlannerAnswer {
  feasible: boolean;
  reason: string;
  nodes: number;
  ms: number;
  budget: number;
}

export interface Precomputed {
  wallThickness: number;
  catalogue: CatalogueEntry[];
  hero: {
    params: EnvironmentParams;
    itemId: string;
    library: HeroLibraryAnswer;
    planner: HeroPlannerAnswer;
    proof: NoFitProof;
  };
}

export const PRECOMPUTED: Precomputed = `;

writeFileSync(out, `${banner}${JSON.stringify(payload, null, 2)};\n`, 'utf8');
console.log(`wrote ${out}`);
